services:
  evershop:
    image: felix5500/very-secure-webshop-ctf:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_PASSWORD: postgres
      DB_USER: postgres
      DB_NAME: postgres
    networks:
      backend:
        ipv4_address: 172.20.0.4
    depends_on:
      - database
    ports:
      - 3000:3000

  database:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/pg_hba.conf:/var/lib/postgresql/pg_hba.conf
      - ./postgres/db-init:/docker-entrypoint-initdb.d
    command: postgres -c hba_file=/var/lib/postgresql/pg_hba.conf
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      backend:
        ipv4_address: 172.20.0.3
  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      backend:
        ipv4_address: 172.20.0.101
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin/config_local.py:/pgadmin4/config_local.py
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgadmin4/pgpass
    expose:
      - 80
    depends_on:
      - database
networks:
  backend:
    name: very-secure-webshop-backend
    driver: bridge
    enable_ipv4: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
